# Generated by Django 5.0.6 on 2024-08-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='discord_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
