# Generated by Django 5.1.1 on 2024-09-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX idx_lower_discord_username
            ON members_user (LOWER(discord_username));
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_lower_discord_username;
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX idx_lower_username
            ON members_user (LOWER(username));
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_lower_username;
            """
        ),
    ]
