# Generated by Django 5.0.6 on 2024-07-04 19:41

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='member',
            name='leetcode_username',
        ),
        migrations.RemoveField(
            model_name='member',
            name='linkedin_username',
        ),
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.JSONField(blank=True, null=True, validators=[members.models.validate_social_field]),
        ),
        migrations.AddField(
            model_name='member',
            name='leetcode',
            field=models.JSONField(blank=True, null=True, validators=[members.models.validate_social_field]),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.JSONField(blank=True, null=True, validators=[members.models.validate_social_field]),
        ),
    ]
