# Generated by Django 4.2.16 on 2024-11-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_lowercase_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
