# Generated by Django 5.0.6 on 2024-08-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_discord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
