# Generated by Django 4.2.17 on 2025-03-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_user_members_use_usernam_82d39a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
