# Generated by Django 5.0.6 on 2024-08-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_discord_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX idx_lower_discord_username
            ON members_member (LOWER(discord_username));
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_lower_discord_username;
            """
        ),
    ]
