# Generated by Django 5.0.6 on 2024-08-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_add_lowercase_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX idx_lower_username
            ON auth_user (LOWER(username));
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_lower_username;
            """
        ),
    ]
