# Generated by Django 5.0.6 on 2024-07-07 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('discord_id', models.CharField(max_length=50, unique=True)),
                ('discord_username', models.CharField(max_length=50)),
            ],
        ),
    ]
