# Generated by Django 5.0.6 on 2024-07-08 03:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_authkey_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authkey',
            name='id',
        ),
        migrations.AlterField(
            model_name='authkey',
            name='discord_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authkey',
            name='discord_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authkey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
