# Generated by Django 4.2.20 on 2025-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file_name",
            field=models.CharField(max_length=255),
        ),
    ]
