version: '3.8'

services:
  db:
    image: postgres:13
    networks:
      - swecc-default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}

volumes:
  postgres_data:

networks:
  swecc-default:
    external: true
    name: swecc-default
