# Generated by Django 4.2.16 on 2024-10-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="reporter_member_id",
            new_name="reported_user_id",
        ),
    ]
