# Generated by Django 5.0.6 on 2024-07-06 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewAvailability",
            fields=[
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interview_availability_slots",
                    models.JSONField(blank=True, null=True),
                ),
                ("mentor_availability_slots", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="InterviewPool",
            fields=[
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "interview_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("date_effective", models.DateTimeField()),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                (
                    "behavioral_questions",
                    models.ManyToManyField(to="questions.behavioralquestion"),
                ),
                (
                    "interviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews_as_interviewee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews_as_interviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technical_question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.technicalquestion",
                    ),
                ),
            ],
        ),
    ]
