# Generated by Django 4.2.17 on 2024-12-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0005_rename_technical_question_interview_technical_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewpool",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
