# Generated by Django 4.2.17 on 2025-02-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0004_alter_cohortstats_applications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CohortStats',
        ),
    ]
