# Generated by Django 4.2.20 on 2025-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cohort", "0007_cohort_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="discord_channel_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cohort",
            name="discord_role_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
