# Generated by Django 4.2.17 on 2024-12-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('channel_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('category_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('channel_type', models.CharField(choices=[('TEXT', 'Text Channel'), ('VOICE', 'Voice Channel'), ('CATEGORY', 'Category'), ('STAGE', 'Stage Channel'), ('FORUM', 'Forum Channel')], max_length=255)),
                ('guild_id', models.BigIntegerField(db_index=True)),
            ],
        ),
    ]
