# Generated by Django 5.0.6 on 2024-07-01 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('topic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BehavioralQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_assigned', models.DateField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('solution', models.TextField()),
                ('follow_ups', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavioral_questions_approved', to='members.member')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_questions_created', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_assigned', models.DateField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('solution', models.TextField()),
                ('follow_ups', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_questions_approved', to='members.member')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_questions_created', to='members.member')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questiontopic')),
            ],
        ),
    ]
