# Generated by Django 5.1.1 on 2024-09-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questiontopic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalquestion',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
