# Generated by Django 4.2.17 on 2024-12-28 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_newgradapplicationstats_internshipapplicationstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplicationstats',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newgradapplicationstats',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
