# Generated by Django 4.2.20 on 2025-04-01 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralDetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("active_until", models.DateField(blank=True, null=True)),
                ("company", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True, null=True)),
                ("expectations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_path", models.CharField(max_length=255)),
                ("uploaded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="referrals.referraldetails",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="referraldetails",
            index=models.Index(
                fields=["status", "member"], name="referrals_r_status_d5ccb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referraldetails",
            index=models.Index(
                fields=["active_until"], name="referrals_r_active__88fd1a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referraldetails",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("member",),
                name="unique_pending_referral_per_member",
            ),
        ),
    ]
