# Generated by Django 4.2.17 on 2024-12-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="key",
            field=models.CharField(max_length=20),
        ),
    ]
