# Generated by Django 4.2.17 on 2024-12-30 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagement', '0002_alter_attendancesession_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discordmessagestats',
            unique_together={('member', 'channel_id')},
        ),
    ]
