# Generated by Django 4.2.17 on 2025-01-03 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_attendancesessionstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesessionstats',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
