# Generated by Django 4.2.17 on 2025-02-08 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cohort", "0005_delete_cohortstats"),
        ("engagement", "0005_attendancesessionstats_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applications", models.IntegerField(default=0)),
                ("onlineAssessments", models.IntegerField(default=0)),
                ("interviews", models.IntegerField(default=0)),
                ("offers", models.IntegerField(default=0)),
                ("dailyChecks", models.IntegerField(default=0)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cohort.cohort"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_member_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
