name: Deploy Server Service
on:
  push:
    branches:
      - main

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-server:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-server:${{ github.sha }}

  deploy_to_swarm:
    runs-on:
      group: EC2
      labels: [self-hosted, deploy]
    
    needs: push_to_dockerhub
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy server service
      run: |
        # Remove the existing service if it exists
        docker service rm swecc_stack_server || true
        
        # Extract environment variables from config
        docker config inspect server_env --pretty | sed -n '/Data:/,$ p' | sed '1d' > env_file.txt

        # Deploy the service with the env file
        docker service create \
          --name swecc_stack_server \
          --network swecc_stack_swecc-network \
          --env-file env_file.txt \
          --replicas 1 \
          --restart-condition any \
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-server:latest

        # Clean up
        rm env_file.txt