name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-server:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/swecc-server:${{ github.sha }}
    - name: Deploy application
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/swecc-server:latest
        options: |
          -p 8000:8000
          -e DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}
          -e DB_HOST=${{ secrets.DB_HOST }}
          -e DB_NAME=${{ secrets.DB_NAME }}
          -e DB_PORT=${{ secrets.DB_PORT }}
          -e DB_USER=${{ secrets.DB_USER }}
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          --name swecc-server-be-container
        run: |
          echo "Container is running"
          # Add any additional commands you want to run inside the container
    - name: Clean up old container
      run: |
        docker stop swecc-server-be-container || true
        docker rm swecc-server-be-container || true
