name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'Marking as stale since there has been no activity for 30 days. Please comment if you are still interested in this issue.'
          stale-pr-message:  'Marking as stale since there has been no activity for 30 days. Will close in 7 days if no activity.'
          days-before-stale: 30
      